# Site settings
title: Green Eyed Soul Studio
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

#baseurl: "/greeneyedsoulstudio"
#url: "https://fbs70.github.io"

github_repo: "https://github.com/fbs70/greeneyedsoulstudio"

social:
  - title: etsy
    url: http://www.etsy.com/shop/greeneyedsoul
  - title: facebook
    url: https://www.facebook.com/pages/Green-Eyed-Soul-Wearable-Art-By-Misti-Marie-Patnode/322709233959
  - title: instagram
    url: https://instagram.com/

# Pagination
paginate: 2
paginate_path: "/post/page:num/"

# Google Analytics
google_analytics_tracking_id:

# Build settings
markdown: kramdown
permalink: pretty
theme: minima
gems:
  # - jekyll-feed
  - jekyll-paginate

include:
  - .nojekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - bower.json
  - node_modules
  - package.json
  - Gruntfile.coffee
  - Rakefile
