# Site settings
title: Green Eyed Soul Studio
tagline: Wearable Art by Misti Patnode
email: your-email@domain.com
description:

baseurl: "/greeneyedsoulstudio"
url: "https://fbs70.github.io"
#baseurl: ""
#url: ""

github_repo: "https://github.com/fbs70/greeneyedsoulstudio"

social:
  - title: etsy
    url: http://www.etsy.com/shop/greeneyedsoul
  - title: facebook
    url: https://www.facebook.com/pages/Green-Eyed-Soul-Wearable-Art-By-Misti-Marie-Patnode/322709233959

# Pagination
paginate: 2
paginate_path: "/post/page:num/"

#permalink
permalink: /:year/:month/:day/:title.html

# Google Analytics
google_analytics_tracking_id:

# Build settings
markdown: kramdown
permalink: pretty
theme: minima
gems:
  # - jekyll-feed
  - jekyll-paginate

include:
  - .nojekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - bower.json
  - node_modules
  - package.json
  - Gruntfile.coffee
  - Rakefile
